# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

desc "Run semantic-release locally"
lane :run_semver_local do
  # See current working dir
  sh "pwd && ls -a"
    # Get the current Git branch
  branch_name = sh("git rev-parse --abbrev-ref HEAD").strip
  UI.message("Current branch: #{branch_name}")

    # Run semantic-release with the current branch
  sh "npx semantic-release --branches #{branch_name} --ci false --tag beta"
version = ENV['PACKAGE_VERSION']
  UI.message("Using version: #{version}")
  # Extract the new version and print it
#   version = get_version_name_from_package_json
  UI.message("New version updated in package.json: #{version}")

  # Commit and push changes if needed
  sh "git add package.json"
  sh "git commit -m 'chore(release): update version to #{version}'"
  sh "git push origin  #{branch_name}"
end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
